version: "3.7"

services:
  app:
    image: kafka-discord-connector:latest
    ports:
      - 9092:9092
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 2181:2181
      - 3030:3030
    volumes:
      - ./:/app
    entrypoint: "/bin/bash setup-and-run.sh"
    command: "touch running.txt"
volumes:
  discord_connector_data:

